import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { LanguageProvider } from "./context/LanguageContext";
import StickyLayoutGuard from "./components/StickyLayoutGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ज्वालामूखी ग्रामिण खानेपानी - ज्वालामूखी, धादिङ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ne">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/* 🌐 Inject Google Translate Init Function */}
        <Script id="google-translate-init" strategy="beforeInteractive">
          {`
            function googleTranslateElementInit() {
              new google.translate.TranslateElement(
                {
                  pageLanguage: "ne",
                  includedLanguages: "en,ne",
                  autoDisplay: false,
                },
                "google_translate_element"
              );
            }
          `}
        </Script>

        {/* 🌐 Load Google Translate Script */}
        <Script
          src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          strategy="beforeInteractive"
        />

        {/* 🔥 Your Application */}
        <LanguageProvider>
          <StickyLayoutGuard />
          {children}
        </LanguageProvider>

      </body>
    </html>
  );
}
